CREATE TABLE ESTUDIANTES
(
    ID_ESTUDIANTE INT,
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    FECHA_NACIMIENTO DATE,
    PROMEDIO DECIMAL(4,2),
    EMAIL VARCHAR(150),
    ACTIVO BOOLEAN,
    FECHA_INSCRIPCION TIMESTAMP
);

CREATE TABLE PRODUCTOS
(
    ID_PRODUCTO INT NOT NULL,

    NOMBRE_PRODUCTO VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,


    PRECIO DECIMAL(10,2) NOT NULL,
    CANTIDAD_STOCK INT DEFAULT 0,


    ID_PROVEEDOR INT,


    FECHA_ALTA DATE NOT NULL,
    ULTIMA_ACTUALIZACION TIMESTAMP
);


CREATE TABLE CLIENTES
(
    ID_CLIENTE INT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE
);


CREATE TABLE PEDIDOS
(
    ID_PEDIDO INT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    FECHA_PEDIDO DATE NOT NULL,
    TOTAL DECIMAL(10,2),

    FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE LIBROS
(
    ID_LIBRO INT PRIMARY KEY,

    TITULO VARCHAR(200) NOT NULL,
    AUTOR VARCHAR(150) NOT NULL,
    ISBN VARCHAR(13) UNIQUE NOT NULL,

    ANIO_PUBLICACION INT,
    NUMERO_PAGINAS INT,
    EDITORIAL VARCHAR(100),

    DISPONIBLE BOOLEAN DEFAULT TRUE,
    CANTIDAD_COPIAS INT DEFAULT 1,

    FECHA_REGISTRO DATE DEFAULT CURRENT_DATE,

    CHECK (ANIO_PUBLICACION > 1000 AND ANIO_PUBLICACION <= EXTRACT(YEAR FROM CURRENT_DATE)),
    CHECK (NUMERO_PAGINAS > 0),
    CHECK (CANTIDAD_COPIAS >= 0)
);

CREATE TABLE CLIENTES
(
    ID_CLIENTE INT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    TELEFONO VARCHAR(20),
    FECHA_REGISTRO DATE DEFAULT CURRENT_DATE
);

CREATE TABLE PEDIDOS (
ID_PEDIDO INT PRIMARY KEY,
ID_CLIENTE INT NOT NULL, 
FECHA_PEDIDO DATE DEFAULT CURRENT_DATE,
TOTAL DECIMAL(10,2) NOT NULL,
ESTADO VARCHAR(20) DEFAULT 'Pendiente',

FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
ON DELETE RESTRICT 
ON
UPDATE CASCADE,

CHECK (TOTAL > 0
),
CHECK
(ESTADO IN
('Pendiente', 'Procesando', 'Enviado', 'Entregado', 'Cancelado'))
);

CREATE TABLE ESTUDIANTES
(
    ID_ESTUDIANTE INT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    FECHA_INGRESO DATE DEFAULT CURRENT_DATE
);

CREATE TABLE CURSOS
(
    ID_CURSO INT PRIMARY KEY,
    NOMBRE_CURSO VARCHAR(100) NOT NULL,
    CODIGO_CURSO VARCHAR(20) UNIQUE NOT NULL,
    CREDITOS INT,
    CHECK (CREDITOS > 0)
);

CREATE TABLE INSCRIPCIONES
(
    ID_INSCRIPCION INT PRIMARY KEY,
    ID_ESTUDIANTE INT NOT NULL,
    ID_CURSO INT NOT NULL,
    FECHA_INSCRIPCION DATE DEFAULT CURRENT_DATE,
    CALIFICACION DECIMAL(4,2),
    ESTADO VARCHAR(20) DEFAULT 'Activo',

    FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTES(ID_ESTUDIANTE)
ON DELETE CASCADE,

    FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO)
ON DELETE CASCADE,


    UNIQUE (ID_ESTUDIANTE, ID_CURSO),

    CHECK (CALIFICACION >= 0 AND CALIFICACION <= 5),
    CHECK (ESTADO IN ('Activo', 'Completado', 'Retirado', 'Reprobado'))
);

CREATE TABLE CLIENTES
(
    ID_CLIENTE INT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    TELEFONO VARCHAR(20),
    DIRECCION TEXT,
    CIUDAD VARCHAR(50),
    FECHA_REGISTRO DATE DEFAULT CURRENT_DATE,
    ACTIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE CATEGORIAS
(
    ID_CATEGORIA INT PRIMARY KEY,
    NOMBRE_CATEGORIA VARCHAR(50) UNIQUE NOT NULL,
    DESCRIPCION TEXT
);

CREATE TABLE PRODUCTOS
(
    ID_PRODUCTO INT PRIMARY KEY,
    NOMBRE_PRODUCTO VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    ID_CATEGORIA INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    STOCK_ACTUAL INT DEFAULT 0,
    STOCK_MINIMO INT DEFAULT 10,
    ACTIVO BOOLEAN DEFAULT TRUE,

    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
    CHECK (PRECIO_UNITARIO > 0),
    CHECK (STOCK_ACTUAL >= 0),
    CHECK (STOCK_MINIMO >= 0)
);

CREATE TABLE PEDIDOS
(
    ID_PEDIDO INT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    FECHA_PEDIDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO VARCHAR(20) DEFAULT 'Pendiente',
    SUBTOTAL DECIMAL(10,2) DEFAULT 0,
    IMPUESTO DECIMAL(10,2) DEFAULT 0,
    TOTAL DECIMAL(10,2) DEFAULT 0,
    OBSERVACIONES TEXT,

    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    CHECK (ESTADO IN ('Pendiente', 'Procesando', 'Enviado', 'Entregado', 'Cancelado')),
    CHECK (SUBTOTAL >= 0),
    CHECK (IMPUESTO >= 0),
    CHECK (TOTAL >= 0)
);

CREATE TABLE DETALLE_PEDIDOS
(
    ID_DETALLE INT PRIMARY KEY,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    DESCUENTO DECIMAL(5,2) DEFAULT 0,
    SUBTOTAL DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO) ON DELETE CASCADE,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
    CHECK (CANTIDAD > 0),
    CHECK (PRECIO_UNITARIO > 0),
    CHECK (DESCUENTO >= 0 AND DESCUENTO <= 100),
    CHECK (SUBTOTAL >= 0)
);

CREATE TABLE PAGOS
(
    ID_PAGO INT PRIMARY KEY,
    ID_PEDIDO INT NOT NULL,
    FECHA_PAGO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MONTO DECIMAL(10,2) NOT NULL,
    METODO_PAGO VARCHAR(30) NOT NULL,
    NUMERO_REFERENCIA VARCHAR(50),
    ESTADO VARCHAR(20) DEFAULT 'Completado',

    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
    CHECK (MONTO > 0),
    CHECK (METODO_PAGO IN ('Efectivo', 'Tarjeta Crédito', 'Tarjeta Débito', 'Transferencia', 'PSE')),
    CHECK (ESTADO IN ('Pendiente', 'Completado', 'Rechazado', 'Reembolsado'))
);

SELECT ID_CLIENTE,
    COUNT(*) as NUM_PEDIDOS,
    SUM(TOTAL) as TOTAL_GASTADO
FROM PEDIDOS
GROUP BY ID_CLIENTE
HAVING COUNT(*) > 5;

SELECT ID_CATEGORIA,
    COUNT(*) as PRODUCTOS_STOCK_BAJO
FROM PRODUCTOS
WHERE STOCK_ACTUAL < STOCK_MINIMO
GROUP BY ID_CATEGORIA
HAVING COUNT(*) >= 3;

UPDATE PRODUCTOS
SET PRECIO_UNITARIO = PRECIO_UNITARIO * 1.10
WHERE ID_CATEGORIA = 1;

UPDATE CLIENTES
SET ACTIVO = FALSE
WHERE ID_CLIENTE NOT IN (
SELECT DISTINCT ID_CLIENTE
FROM PEDIDOS
WHERE FECHA_PEDIDO >= CURRENT_DATE - INTERVAL
'6 months'
);

UPDATE PRODUCTOS
SET STOCK_ACTUAL = STOCK_ACTUAL - 5
WHERE ID_PRODUCTO = 201
    AND STOCK_ACTUAL >= 5;

BEGIN TRANSACTION;

UPDATE PRODUCTOS
SET STOCK_ACTUAL = STOCK_ACTUAL - 10
WHERE ID_PRODUCTO = 101 AND STOCK_ACTUAL >= 10;

UPDATE PRODUCTOS
SET STOCK_ACTUAL = STOCK_ACTUAL + 10
WHERE ID_PRODUCTO = 101;

INSERT INTO MOVIMIENTOS_INVENTARIO
    (ID_PRODUCTO, TIPO_MOVIMIENTO, CANTIDAD, FECHA)
VALUES
    (101, 'Transferencia', 10, CURRENT_TIMESTAMP);

COMMIT;

CREATE INDEX idx_clientes_email
ON CLIENTES(EMAIL);

CREATE INDEX idx_pedidos_cliente_fecha
ON PEDIDOS(ID_CLIENTE, FECHA_PEDIDO);

CREATE UNIQUE INDEX idx_productos_codigo
ON PRODUCTOS(CODIGO_PRODUCTO);

DROP INDEX idx_clientes_email;

-- ==========================================================
-- 1. Vista resumen de clientes
-- ==========================================================
CREATE OR REPLACE VIEW VISTA_CLIENTES_RESUMEN AS
SELECT
    C.ID_CLIENTE,
    C.NOMBRE,
    C.APELLIDO,
    C.EMAIL,
    COUNT(P.ID_PEDIDO) AS TOTAL_PEDIDOS,
    COALESCE(SUM(P.TOTAL), 0) AS TOTAL_GASTADO,
    MAX(P.FECHA_PEDIDO) AS ULTIMA_COMPRA
FROM CLIENTES C
    LEFT JOIN PEDIDOS P ON C.ID_CLIENTE = P.ID_CLIENTE
GROUP BY C.ID_CLIENTE, C.NOMBRE, C.APELLIDO, C.EMAIL;

SELECT *
FROM VISTA_CLIENTES_RESUMEN
WHERE TOTAL_GASTADO > 1000000;

-- ==========================================================
-- 2. Vista productos bajo stock
-- ==========================================================
CREATE OR REPLACE VIEW VISTA_PRODUCTOS_BAJO_STOCK AS
SELECT
    P.ID_PRODUCTO,
    P.NOMBRE_PRODUCTO,
    C.NOMBRE_CATEGORIA,
    P.STOCK_ACTUAL,
    P.STOCK_MINIMO,
    (P.STOCK_MINIMO - P.STOCK_ACTUAL) AS DEFICIT
FROM PRODUCTOS P
    JOIN CATEGORIAS C ON P.ID_CATEGORIA = C.ID_CATEGORIA
WHERE P.STOCK_ACTUAL < P.STOCK_MINIMO
    AND P.ACTIVO = TRUE;

-- ==========================================================
-- 3. Procedimiento registrar cliente
-- ==========================================================
DELIMITER $$
CREATE PROCEDURE sp_registrar_cliente(
    IN nombre VARCHAR
(100),
    IN apellido VARCHAR
(100),
    IN email VARCHAR
(100),
    IN telefono VARCHAR
(20),
    IN ciudad VARCHAR
(50)
)
BEGIN
    IF EXISTS (SELECT 1
    FROM CLIENTES
    WHERE EMAIL = email) THEN
        SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT
    = 'El email ya está registrado';
END
IF;

    INSERT INTO CLIENTES
    (NOMBRE, APELLIDO, EMAIL, TELEFONO, CIUDAD, FECHA_REGISTRO, ACTIVO)
VALUES
    (nombre, apellido, email, telefono, ciudad, CURRENT_DATE
(), TRUE);

SELECT LAST_INSERT_ID() AS NUEVO_ID_CLIENTE;
END$$
DELIMITER ;

CALL sp_registrar_cliente
('Carlos', 'Rodríguez', 'carlos@email.com', '3009876543', 'Medellín');

-- ==========================================================
-- 4. Tabla auditoría
-- ==========================================================
CREATE TABLE
IF NOT EXISTS AUDITORIA_PRECIOS
(
    ID_AUDITORIA INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUCTO INT NOT NULL,
    PRECIO_ANTERIOR DECIMAL
(10,2),
    PRECIO_NUEVO DECIMAL
(10,2),
    FECHA_CAMBIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO VARCHAR
(50)
);

-- ==========================================================
-- 5. Trigger auditoría precios
-- ==========================================================
DELIMITER $$
CREATE TRIGGER trg_auditoria_precio_producto
AFTER
UPDATE ON PRODUCTOS
FOR EACH ROW
BEGIN
    IF OLD.PRECIO_UNITARIO <> NEW.PRECIO_UNITARIO THEN
    INSERT INTO AUDITORIA_PRECIOS
        (ID_PRODUCTO, PRECIO_ANTERIOR, PRECIO_NUEVO, USUARIO)
    VALUES
        (NEW.ID_PRODUCTO, OLD.PRECIO_UNITARIO, NEW.PRECIO_UNITARIO, CURRENT_USER
    ());
END
IF;
END$$
DELIMITER ;

-- ==========================================================
-- 6. CTE estadísticas de clientes
-- ==========================================================
WITH
    VentasPorCliente
    AS
    (
        SELECT ID_CLIENTE, COUNT(*) AS NUM_PEDIDOS, SUM(TOTAL) AS TOTAL_GASTADO
        FROM PEDIDOS
        WHERE ESTADO = 'Entregado'
        GROUP BY ID_CLIENTE
    ),
    CategoriasCliente
    AS
    (
        SELECT
            ID_CLIENTE,
            NUM_PEDIDOS,
            TOTAL_GASTADO,
            CASE
            WHEN TOTAL_GASTADO >= 5000000 THEN 'Premium'
            WHEN TOTAL_GASTADO >= 1000000 THEN 'Regular'
            ELSE 'Básico'
        END AS CATEGORIA
        FROM VentasPorCliente
    )
SELECT
    C.NOMBRE,
    C.APELLIDO,
    CC.NUM_PEDIDOS,
    CC.TOTAL_GASTADO,
    CC.CATEGORIA
FROM CategoriasCliente CC
    JOIN CLIENTES C ON CC.ID_CLIENTE = C.ID_CLIENTE
WHERE CC.CATEGORIA = 'Premium'
ORDER BY CC.TOTAL_GASTADO DESC;

-- ==========================================================
-- 7. Clasificación de clientes
-- ==========================================================
SELECT
    C.NOMBRE,
    COUNT(P.ID_PEDIDO) AS NUM_COMPRAS,
    SUM(P.TOTAL) AS TOTAL_GASTADO,
    CASE
        WHEN SUM(P.TOTAL) >= 10000000 THEN 'VIP'
        WHEN SUM(P.TOTAL) >= 5000000 THEN 'Gold'
        WHEN SUM(P.TOTAL) >= 1000000 THEN 'Silver'
        WHEN COUNT(P.ID_PEDIDO) >= 5 THEN 'Frecuente'
        ELSE 'Regular'
    END AS CATEGORIA_CLIENTE,
    CASE
        WHEN MAX(P.FECHA_PEDIDO) < DATE_SUB(CURRENT_DATE(), INTERVAL
180 DAY) THEN 'Inactivo'
        WHEN MAX
(P.FECHA_PEDIDO) < DATE_SUB
(CURRENT_DATE
(), INTERVAL 90 DAY) THEN 'En Riesgo'
        ELSE 'Activo'
END AS ESTADO_ACTIVIDAD
FROM CLIENTES C
LEFT JOIN PEDIDOS P ON C.ID_CLIENTE = P.ID_CLIENTE
GROUP BY C.ID_CLIENTE, C.NOMBRE;

-- ==========================================================
-- 8. Ventas mensuales
-- ==========================================================
SELECT
    YEAR(FECHA_PEDIDO) AS ANO,
    MONTH(FECHA_PEDIDO) AS MES,
    COUNT(*) AS NUM_PEDIDOS,
    SUM(TOTAL) AS VENTAS_TOTALES,
    AVG(TOTAL) AS TICKET_PROMEDIO
FROM PEDIDOS
WHERE FECHA_PEDIDO >= DATE_SUB(CURRENT_DATE
(), INTERVAL 1 YEAR)
  AND ESTADO = 'Entregado'
GROUP BY YEAR
(FECHA_PEDIDO), MONTH
(FECHA_PEDIDO)
ORDER BY ANO, MES;

-- ==========================================================
-- 9. Movil 7 días
-- ==========================================================
WITH
    VentasDiarias
    AS
    (
        SELECT DATE(FECHA_PEDIDO) AS FECHA, SUM(TOTAL) AS VENTAS
        FROM PEDIDOS
        WHERE ESTADO = 'Entregado'
        GROUP BY DATE(FECHA_PEDIDO)
    )
SELECT
    FECHA,
    VENTAS,
    AVG(VENTAS) OVER (ORDER BY FECHA ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS PROMEDIO_MOVIL_7_DIAS,
    VENTAS - LAG(VENTAS, 7) OVER (ORDER BY FECHA) AS CAMBIO_SEMANAL,
    (VENTAS - LAG(VENTAS, 7) OVER (ORDER BY FECHA)) /
        NULLIF(LAG(VENTAS, 7) OVER (ORDER BY FECHA), 0) * 100 AS CAMBIO_PORCENTUAL
FROM VentasDiarias
ORDER BY FECHA DESC
LIMIT 30;

-- ==========================================================
-- 10. Instituciones
-- ==========================================================
CREATE TABLE IF NOT EXISTS INSTITUCIONES
(
    ID_INSTITUCION INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR
(200) NOT NULL,
    TIPO_INSTITUCION ENUM
('Universidad', 'Instituto', 'Colegio') NOT NULL,
    CIUDAD VARCHAR
(100),
    DIRECCION TEXT,
    TELEFONO VARCHAR
(20),
    EMAIL VARCHAR
(100) UNIQUE,
    FECHA_FUNDACION DATE,
    ACTIVA BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================================
-- 11. Programas académicos
-- ==========================================================
CREATE TABLE
IF NOT EXISTS PROGRAMAS_ACADEMICOS
(
    ID_PROGRAMA INT PRIMARY KEY AUTO_INCREMENT,
    ID_INSTITUCION INT NOT NULL,
    CODIGO_PROGRAMA VARCHAR
(20) UNIQUE NOT NULL,
    NOMBRE_PROGRAMA VARCHAR
(200) NOT NULL,
    NIVEL ENUM
('Técnico','Tecnológico','Profesional','Especialización','Maestría','Doctorado'),
    DURACION_SEMESTRES INT CHECK
(DURACION_SEMESTRES > 0),
    CREDITOS_TOTALES INT CHECK
(CREDITOS_TOTALES > 0),
    MODALIDAD ENUM
('Presencial','Virtual','Semi-presencial') DEFAULT 'Presencial',
    ACTIVO BOOLEAN DEFAULT TRUE,
    FOREIGN KEY
(ID_INSTITUCION) REFERENCES INSTITUCIONES
(ID_INSTITUCION)
);

-- ==========================================================
-- 12. Estudiantes
-- ==========================================================
CREATE TABLE
IF NOT EXISTS ESTUDIANTES
(
    ID_ESTUDIANTE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_DOCUMENTO ENUM
('CC','TI','CE','Pasaporte') NOT NULL,
    NUMERO_DOCUMENTO VARCHAR
(20) UNIQUE NOT NULL,
    NOMBRES VARCHAR
(100) NOT NULL,
    APELLIDOS VARCHAR
(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    GENERO ENUM
('M','F','Otro','Prefiero no decir'),
    EMAIL VARCHAR
(150) UNIQUE NOT NULL,
    TELEFONO VARCHAR
(20),
    CELULAR VARCHAR
(20),
    DIRECCION TEXT,
    CIUDAD VARCHAR
(100),
    DEPARTAMENTO VARCHAR
(100),
    ESTRATO INT CHECK
(ESTRATO BETWEEN 1 AND 6),
    ESTADO_CIVIL ENUM
('Soltero','Casado','Unión Libre','Divorciado','Viudo'),
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVO BOOLEAN DEFAULT TRUE,
    CHECK
(FECHA_NACIMIENTO < DATE_SUB
(CURRENT_DATE
(), INTERVAL 15 YEAR))
);

-- ==========================================================
-- 13. Inscripciones
-- ==========================================================
CREATE TABLE
IF NOT EXISTS INSCRIPCIONES
(
    ID_INSCRIPCION INT PRIMARY KEY AUTO_INCREMENT,
    ID_ESTUDIANTE INT NOT NULL,
    ID_PROGRAMA INT NOT NULL,
    FECHA_INSCRIPCION DATE DEFAULT CURRENT_DATE
(),
    SEMESTRE_INGRESO INT CHECK
(SEMESTRE_INGRESO BETWEEN 1 AND 2),
    ANO_INGRESO INT CHECK
(ANO_INGRESO >= 2000),
    ESTADO ENUM
('Activo','Graduado','Retirado','Suspendido','Aplazado') DEFAULT 'Activo',
    PROMEDIO_ACUMULADO DECIMAL
(4,2) DEFAULT 0.00 CHECK
(PROMEDIO_ACUMULADO BETWEEN 0 AND 5),
    CREDITOS_APROBADOS INT DEFAULT 0 CHECK
(CREDITOS_APROBADOS >= 0),
    FECHA_ESTADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OBSERVACIONES TEXT,
    UNIQUE
(ID_ESTUDIANTE, ID_PROGRAMA),
    FOREIGN KEY
(ID_ESTUDIANTE) REFERENCES ESTUDIANTES
(ID_ESTUDIANTE),
    FOREIGN KEY
(ID_PROGRAMA) REFERENCES PROGRAMAS_ACADEMICOS
(ID_PROGRAMA)
);

-- ==========================================================
-- 14. Cursos
-- ==========================================================
CREATE TABLE
IF NOT EXISTS CURSOS
(
    ID_CURSO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PROGRAMA INT NOT NULL,
    CODIGO_CURSO VARCHAR
(20) UNIQUE NOT NULL,
    NOMBRE_CURSO VARCHAR
(200) NOT NULL,
    CREDITOS INT NOT NULL CHECK
(CREDITOS > 0),
    HORAS_SEMANALES INT CHECK
(HORAS_SEMANALES > 0),
    NIVEL_SEMESTRE INT CHECK
(NIVEL_SEMESTRE > 0),
    TIPO ENUM
('Obligatoria','Electiva','Práctica','Proyecto') DEFAULT 'Obligatoria',
    PREREQUISITOS TEXT,
    DESCRIPCION TEXT,
    ACTIVO BOOLEAN DEFAULT TRUE,
    FOREIGN KEY
(ID_PROGRAMA) REFERENCES PROGRAMAS_ACADEMICOS
(ID_PROGRAMA)
);

-- ==========================================================
-- 15. Calificaciones
-- ==========================================================
CREATE TABLE
IF NOT EXISTS CALIFICACIONES
(
    ID_CALIFICACION INT PRIMARY KEY AUTO_INCREMENT,
    ID_INSCRIPCION INT NOT NULL,
    ID_CURSO INT NOT NULL,
    PERIODO_ACADEMICO VARCHAR
(10) NOT NULL,
    ANO INT NOT NULL,
    NOTA_DEFINITIVA DECIMAL
(4,2) CHECK
(NOTA_DEFINITIVA BETWEEN 0 AND 5),
    ESTADO_CURSO ENUM
('Cursando','Aprobado','Reprobado','Retirado','Validado'),
    PORCENTAJE_ASISTENCIA DECIMAL
(5,2) CHECK
(PORCENTAJE_ASISTENCIA BETWEEN 0 AND 100),
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON
UPDATE CURRENT_TIMESTAMP,
    OBSERVACIONES TEXT,
    UNIQUE (ID_INSCRIPCION, ID_CURSO, PERIODO_ACADEMICO, ANO),
    FOREIGN KEY
(ID_INSCRIPCION) REFERENCES INSCRIPCIONES
(ID_INSCRIPCION),
    FOREIGN KEY
(ID_CURSO) REFERENCES CURSOS
(ID_CURSO)
);

-- ==========================================================
-- 16. Estadísticas por programa
-- ==========================================================
WITH
    EstadisticasPrograma
    AS
    (
        SELECT
            PA.NOMBRE_PROGRAMA,
            COUNT(DISTINCT I.ID_ESTUDIANTE) AS TOTAL_ESTUDIANTES,
            AVG(I.PROMEDIO_ACUMULADO) AS PROMEDIO_PROGRAMA,
            SUM(CASE WHEN I.ESTADO = 'Activo' THEN 1 ELSE 0 END) AS ESTUDIANTES_ACTIVOS,
            SUM(CASE WHEN I.ESTADO = 'Graduado' THEN 1 ELSE 0 END) AS GRADUADOS,
            SUM(CASE WHEN I.ESTADO = 'Retirado' THEN 1 ELSE 0 END) AS RETIRADOS
        FROM PROGRAMAS_ACADEMICOS PA
            LEFT JOIN INSCRIPCIONES I ON PA.ID_PROGRAMA = I.ID_PROGRAMA
        GROUP BY PA.ID_PROGRAMA, PA.NOMBRE_PROGRAMA
    )
SELECT *,
    ROUND(GRADUADOS * 100.0 / NULLIF(TOTAL_ESTUDIANTES, 0), 2) AS TASA_GRADUACION,
    ROUND(RETIRADOS * 100.0 / NULLIF(TOTAL_ESTUDIANTES, 0), 2) AS TASA_DESERCION
FROM EstadisticasPrograma
ORDER BY TOTAL_ESTUDIANTES DESC;

-- ==========================================================
-- 17. Top estudiantes por promedio
-- ==========================================================
SELECT
    E.NUMERO_DOCUMENTO,
    CONCAT(E.NOMBRES, ' ', E.APELLIDOS) AS NOMBRE_COMPLETO,
    PA.NOMBRE_PROGRAMA,
    I.PROMEDIO_ACUMULADO,
    I.CREDITOS_APROBADOS,
    RANK() OVER (PARTITION BY I.ID_PROGRAMA ORDER BY I.PROMEDIO_ACUMULADO DESC) AS POSICION_PROGRAMA
FROM ESTUDIANTES E
    JOIN INSCRIPCIONES I ON E.ID_ESTUDIANTE = I.ID_ESTUDIANTE
    JOIN PROGRAMAS_ACADEMICOS PA ON I.ID_PROGRAMA = PA.ID_PROGRAMA
WHERE I.ESTADO = 'Activo'
    AND I.PROMEDIO_ACUMULADO > 0
ORDER BY I.ID_PROGRAMA, I.PROMEDIO_ACUMULADO DESC;

-- ==========================================================
-- 18. Cursos con mayor reprobación
-- ==========================================================
SELECT
    C.CODIGO_CURSO,
    C.NOMBRE_CURSO,
    PA.NOMBRE_PROGRAMA,
    COUNT(*) AS TOTAL_MATRICULAS,
    SUM(CASE WHEN CAL.ESTADO_CURSO = 'Reprobado' THEN 1 ELSE 0 END) AS REPROBADOS,
    ROUND(SUM(CASE WHEN CAL.ESTADO_CURSO = 'Reprobado' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2)
        AS PORCENTAJE_REPROBACION,
    AVG(CAL.NOTA_DEFINITIVA) AS PROMEDIO_NOTA
FROM CURSOS C
    JOIN PROGRAMAS_ACADEMICOS PA ON C.ID_PROGRAMA = PA.ID_PROGRAMA
    JOIN CALIFICACIONES CAL ON C.ID_CURSO = CAL.ID_CURSO
WHERE CAL.ESTADO_CURSO IN ('Aprobado', 'Reprobado')
GROUP BY C.ID_CURSO, C.CODIGO_CURSO, C.NOMBRE_CURSO, PA.NOMBRE_PROGRAMA
HAVING COUNT(*) >= 10
ORDER BY PORCENTAJE_REPROBACION DESC
LIMIT 20;
